# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19UCWC--UTPkIK5WyyJeXXnoNbbJ2Yva4
"""



import sqlite3

# Connect to SQLite database (creates it if it doesn't exist)
conn = sqlite3.connect('sales_data.db')
cursor = conn.cursor()

# Create sales table
cursor.execute('''
CREATE TABLE IF NOT EXISTS sales (
    product TEXT,
    quantity INTEGER,
    price REAL
)
''')

# Insert sample sales data for CSE-related products
sales_data = [
    ('VSCode Premium', 50, 49.99),
    ('CloudCompute Pro', 30, 199.99),
    ('SecureAuth API', 20, 149.00),
    ('AI DevKit', 10, 299.00),
    ('VSCode Premium', 25, 49.99),
    ('CloudCompute Pro', 15, 199.99),
    ('AI DevKit', 8, 299.00),
    ('SecureAuth API', 18, 149.00)
]

cursor.executemany('''
INSERT INTO sales (product, quantity, price)
VALUES (?, ?, ?)
''', sales_data)

conn.commit()
conn.close()

print("✅ Sales database created and sample data inserted.")

import pandas as pd

# Reconnect to database
conn = sqlite3.connect('sales_data.db')

# SQL query to summarize sales by product
query = '''
SELECT
    product,
    SUM(quantity) AS total_units_sold,
    ROUND(SUM(quantity * price), 2) AS total_revenue
FROM sales
GROUP BY product
ORDER BY total_revenue DESC
'''

df = pd.read_sql_query(query, conn)
conn.close()

# Display the DataFrame
print("📊 Sales Summary:")
print(df)

import matplotlib.pyplot as plt

# Plot revenue by product
df.plot(kind='bar', x='product', y='total_revenue', color='royalblue', legend=False)
plt.title('Total Revenue by Product')
plt.xlabel('Software Product')
plt.ylabel('Revenue (USD)')
plt.xticks(rotation=45)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()